services:
  markitdown:
    build: 
      context: ./markitdown-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./markitdown-service/app:/app/app  # Keep this for development hot reload
      - markitdown_data:/app/data
      - markitdown_logs:/app/logs
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=sqlite:///./data/api_keys.db
      - API_KEY_AUTH_ENABLED=true
      - SECRET_KEY=${SECRET_KEY:-default-secret-key-change-in-production}
      - ADMIN_API_KEY=${ADMIN_API_KEY:-admin-key-change-in-production}
      - LOG_LEVEL=DEBUG
    command: >
      sh -c "python manage.py init --yes &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  test:
    build: 
      context: ./markitdown-service
      dockerfile: Dockerfile
    volumes:
      - ./markitdown-service/app:/app/app
      - test_data:/app/data
      - test_logs:/app/logs
    environment:
      - ENVIRONMENT=test
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:///./data/test_api_keys.db
      - API_KEY_AUTH_ENABLED=true
      - SECRET_KEY=test-secret-key
      - ADMIN_API_KEY=test-admin-key
      - LOG_LEVEL=WARNING
    entrypoint: python -m pytest
    command: /app/tests/test_api.py -v --capture=no
    depends_on:
      markitdown:
        condition: service_healthy
    profiles:
      - test

volumes:
  markitdown_data:
    name: markitdown_data
  markitdown_logs:
    name: markitdown_logs
  test_data:
    name: markitdown_test_data
  test_logs:
    name: markitdown_test_logs

networks:
  default:
    driver: bridge